name: Build Arduino sketch

on:
  push:
    branches: ["Arduino"]

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - ./
          libraries: |
            - name: WiFiNINA
            - name:
