name: Test REST API

on:
  push:
    branches:
      - backend-*
  workflow_dispatch:

jobs:
  build:
    if: ${{ contains(github.event.head_commit.message, '#test') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Create and start virtual enviroment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test Flask app
        run: |
          pytest
